# Generated by Buildr 1.4.19, change to your liking


# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "ww"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

LANTERNA = 'com.googlecode.lanterna:lanterna:jar:2.1.7'

desc "The WW Project"
define "ww" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  package(:jar).with(:manifest=>_('META-INF/MANIFEST.MF')).merge(LANTERNA)
  compile.with LANTERNA
  manifest["Implementation-Vendor"] = COPYRIGHT
end
